Updates to handle_summary_state fuction
lsst-dm/HeaderService pull request #120
Opened 2023-05-04 19:37 UTC by menanteau

Updates to handle_summary_state

2023-05-04 20:46 UTC, srp3rd requested changes
Additionally, the end_evt_timeout_task list isn't cleared after cancel_timeout_tasks() is called.  If this is called again later, all of the previously canceled tasks are still in the list, and cancel() will be called on each of those again.  I'm not sure what will happen if you call cancel() twice on the same task.

2023-05-04 20:46 UTC, srp3rd commented on python/HeaderService/hslib_salobj.py
> +            self.define_s3bucket()
If this line fails, it throws an exception - instead of that, do you want to call self.fault() instead?

2023-05-04 20:46 UTC, srp3rd commented on python/HeaderService/hslib_salobj.py
> +            self.define_s3bucket()
Also check_services() is called from prepare() on line 52, which if s3 fails will cause an exception.  You probably want to remove check_services() from prepare(), since you all it on line 122.

2023-05-05 20:41 UTC, menanteau commented on python/HeaderService/hslib_salobj.py
> +            self.define_s3bucket()
Thanks. I changed the code as you suggested.

2023-05-09 14:59 UTC, merged